// frontend/src/Components/Footer/Footer.jsx
import React, { useEffect } from "react";
import { Toast } from "bootstrap";

import "./Footer.css";

import mdgt from "./mdgt.png";

export default function Footer() {
  useEffect(() => {
    const toastItem = document.getElementById("toast");
    const toast = new Toast(toastItem);

    const toastBtnAccept = document.getElementById("btnAccept");
    toastBtnAccept.addEventListener("click", () => {
      setCookie("allowCookies", "1", 7);
      toast.hide();
    });

    function setCookie(name, value, days) {
      var expires = "";
      if (days) {
        var date = new Date();
        date.setTime(date.getTime() + days * 24 * 60 * 60 * 1000);
        expires = "; expires=" + date.toUTCString();
      }
      document.cookie = name + "=" + (value || "") + expires + "; path=/";
    }
    function getCookie(name) {
      var nameEQ = name + "=";
      var ca = document.cookie.split(";");
      for (var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) === " ") c = c.substring(1, c.length);
        if (c.indexOf(nameEQ) === 0)
          return c.substring(nameEQ.length, c.length);
      }
      return null;
    }

    function cookieConsent() {
      if (!getCookie("allowCookies")) {
        toast.show();
      }
    }

    cookieConsent();
  }, []);

  return (
    <>
      <footer className="footer__container">
        <div className="copy">
          РАЗРАБОТАНО ГЕОТЕХНИЧЕСКОЙ ЛАБОРАТОРИЕЙ МОСТДОРГЕОТРЕСТ
        </div>
        <div className="container_contact" id="contact">
          <div className="container-mdgt">
            <div className="row">
              <div className="col-md-3 col-sm-6">
                <div className="contacts__double-contact">
                  <div className="">
                    <h3 className="contacts__header">
                      <i className="bi bi-envelope"></i> Почта:
                    </h3>
                    <div className="contacts__description">
                      <a
                        href="mailto:mostdorgeotrest@mail.ru"
                        target="_blank"
                        rel="noreferrer"
                        className="contacts__link"
                      >
                        support@mdgt.ru
                      </a>
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-md-3 col-sm-6">
                <div className="contacts__double-contact">
                  <div className="">
                    <h3 className="contacts__header">
                      <i className="bi bi-globe"></i> Веб-сайт:
                    </h3>
                    <div className="contacts__description">
                      <a
                        href="https://mdgt.site/"
                        target="_blank"
                        rel="noreferrer"
                        className="contacts__link"
                      >
                        mdgt.site
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="footer__logo">
          <a
            href="https://mdgt.ru/"
            target="_blank"
            rel="noreferrer"
            className="mb-3 me-2 mb-md-0 text-muted_mdgt text-decoration-none lh-1"
          >
            <img className="footer__img" src={mdgt} alt="логотип МДГТ" />
          </a>
          <span className="text-muted_mdgt">
            &copy; Мостдоргеотрест {new Date().getFullYear()}
          </span>
        </div>
        <div className="footer__docs">
          <a
            className="footer__docs-link"
            href="/static/docs/Согласие_на_обработку_ПД_на сайт.pdf"
            target="_blank"
            rel="noreferrer"
          >
            Согласие на обработку персональных данных
          </a>
          <a
            className="footer__docs-link"
            href="/static/docs/Политика_на сайт.pdf"
            target="_blank"
            rel="noreferrer"
          >
            Политика конфиденциальности
          </a>
        </div>

        <div
          className="modal fade"
          id="exampleModal"
          tabIndex="-1"
          aria-labelledby="exampleModalLabel"
          aria-hidden="true"
        >
          <div className="modal-dialog modal-lg modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title" id="exampleModalLabel">
                  На карте
                </h5>
                <button
                  type="button"
                  className="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                ></button>
              </div>
              <div className="modal-body">
                <div className="normalMap" id="mapId">
                  <iframe
                    title="map"
                    id="map_702049289"
                    frameBorder="0"
                    width="100%"
                    height="600px"
                    sandbox="allow-modals allow-forms allow-scripts allow-same-origin allow-popups allow-top-navigation-by-user-activation"
                  ></iframe>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="fixed-bottom p-4">
          <div
            className="toast text-white w-100 mw-100"
            id="toast"
            role="alert"
            data-bs-autohide="false"
            style={{ backgroundColor: "var(--text-color)" }}
          >
            <div className="toast-body p-4 d-flex flex-column">
              <h4>Мы используем файлы cookie.</h4>
              <p>
                Мы используем Cookies в том числе с использованием сервиса
                веб-аналитики &quot;Яндекс.Метрика&quot;. Продолжая использовать
                наш сайт, вы даете{" "}
                <a
                  className="contacts__link"
                  href="/static/docs/Согласие_на_обработку_ПД_на сайт.pdf"
                >
                  согласие
                </a>{" "}
                на обработку данных Cookies в том числе с использованием сервиса
                веб-аналитики &quot;Яндекс.Метрика&quot; в соответствии с{" "}
                <a
                  className="contacts__link"
                  href="/static/docs/Политика_на сайт.pdf"
                >
                  Политикой
                </a>
                .
              </p>
              <div className="ms-auto">
                <button type="button" className="btn btn-light" id="btnAccept">
                  Принять
                </button>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </>
  );
}

// frontend-svelte/src/lib/components/Footer.svelte
<script>
</script>

<footer class="footer">
  <div class="footer__dev">
    РАЗРАБОТАНО ГЕОТЕХНИЧЕСКОЙ ЛАБОРАТОРИЕЙ МОСТДОРГЕОТРЕСТ
  </div>

  <div class="footer__contacts" id="contact">
    <div class="footer__contact-group">
      <h3 class="footer__contact-title">
        <i class="ri-mail-line"></i> Почта:
      </h3>
      <a href="mailto:mostdorgeotrest@mail.ru" class="footer__contact-link" target="_blank" rel="noreferrer">
        support@mdgt.ru
      </a>
    </div>

    <div class="footer__contact-group">
      <h3 class="footer__contact-title">
        <i class="ri-global-line"></i> Веб-сайт:
      </h3>
      <a href="https://mdgt.site/" class="footer__contact-link" target="_blank" rel="noreferrer">
        mdgt.site
      </a>
    </div>
  </div>

  <div class="footer__bottom">
    <a href="https://mdgt.ru/" target="_blank" rel="noreferrer" class="footer__logo-link">
      <img src="/images/mdgt.png" alt="МДГТ" class="footer__logo-img" />
    </a>
    <span class="footer__copy">&copy; Мостдоргеотрест {new Date().getFullYear()}</span>
  </div>

  <div class="footer__docs">
    <a
      class="footer__doc-link"
      href="/static/docs/Согласие_на_обработку_ПД_на сайт.pdf"
      target="_blank"
      rel="noreferrer"
    >
      Согласие на обработку персональных данных
    </a>
    <a
      class="footer__doc-link"
      href="/static/docs/Политика_на сайт.pdf"
      target="_blank"
      rel="noreferrer"
    >
      Политика конфиденциальности
    </a>
  </div>
</footer>

<style>
  .footer {
    flex: 0 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    margin-top: 4rem;
    padding: 2rem 1.5rem 1rem;
    background: rgba(255, 255, 255, 0.03);
    border-top: 1px solid var(--glass-border);
  }

  .footer__dev {
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.15em;
    color: var(--text-muted);
    text-align: center;
  }

  .footer__contacts {
    display: flex;
    gap: 3rem;
    flex-wrap: wrap;
    justify-content: center;
  }

  .footer__contact-group {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .footer__contact-title {
    font-size: 0.9rem;
    color: var(--text-secondary);
    display: flex;
    align-items: center;
    gap: 0.35rem;
  }

  .footer__contact-link {
    color: var(--text-muted);
    font-size: 0.85rem;
  }

  .footer__contact-link:hover {
    color: var(--accent-light);
  }

  .footer__bottom {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding-top: 0.5rem;
    border-top: 1px solid var(--glass-border);
    width: 100%;
    justify-content: center;
  }

  .footer__logo-img {
    width: 40px;
    height: 40px;
    opacity: 0.7;
    transition: var(--transition);
  }

  .footer__logo-img:hover {
    opacity: 1;
  }

  .footer__copy {
    color: var(--text-muted);
    font-size: 0.8rem;
  }

  .footer__docs {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.2rem;
  }

  .footer__doc-link {
    font-size: 0.7rem;
    color: var(--text-muted);
    text-decoration: underline;
  }

  .footer__doc-link:hover {
    color: var(--accent-light);
  }
</style>
